// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Wu, Chien Yin and Yeh, Hsiao Li"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to update a event",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateEventFormat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/events/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to create an event",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EventFormat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/events/{event_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "event id",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/groups/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer eyJhbGcikDCEVLw0xRO8CzTg",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer eyJNoCkSqDCEVLw0xRO8CzTg",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to create an group",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createGroupFormat"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer eyJhbGcikDCEVLw0xRO8CzTg",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "7",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/timeblocks/": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to update an event",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Timeblock"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to create an event",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Timeblock"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/timeblocks/export": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to import timeblocks",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTimeblockExportFormat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/timeblocks/import": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to import timeblocks",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTimeblockImportFormat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/timeblocks/{event_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "event id",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/timeblocks/{event_id}/preview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeblock"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "event id",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "The body to create a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Update"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "The body to create a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users/login/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "The body to login a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users/resetPassword": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "The body to create a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ForgotInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "EventFormat": {
            "type": "object",
            "required": [
                "dateOrDays",
                "endTime",
                "eventName",
                "isPriorityEnabled",
                "startTime"
            ],
            "properties": {
                "dateOrDays": {
                    "description": "required",
                    "type": "boolean",
                    "example": true
                },
                "endDate": {
                    "description": "optional",
                    "type": "string",
                    "example": "2021-01-02T12:00:00+08:00"
                },
                "endDay": {
                    "description": "optional",
                    "type": "string",
                    "example": "7"
                },
                "endTime": {
                    "description": "required",
                    "type": "string",
                    "example": "2100"
                },
                "eventName": {
                    "description": "required",
                    "type": "string",
                    "example": "OR first meet"
                },
                "isPriorityEnabled": {
                    "description": "required",
                    "type": "boolean",
                    "example": true
                },
                "startDate": {
                    "description": "optional",
                    "type": "string",
                    "example": "2021-01-01T12:00:00+08:00"
                },
                "startDay": {
                    "description": "optional",
                    "type": "string",
                    "example": "1"
                },
                "startTime": {
                    "description": "required",
                    "type": "string",
                    "example": "0900"
                }
            }
        },
        "GetUserResponse": {
            "type": "object",
            "required": [
                "password_answer",
                "status",
                "user_id",
                "username"
            ],
            "properties": {
                "password_answer": {
                    "type": "string",
                    "example": "NTU"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                },
                "user_id": {
                    "type": "string",
                    "example": "christine891225"
                },
                "username": {
                    "type": "string",
                    "example": "Christine Wang"
                }
            }
        },
        "Login": {
            "type": "object",
            "required": [
                "password",
                "userId"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "userId": {
                    "type": "string",
                    "example": "christine891225"
                }
            }
        },
        "Register": {
            "type": "object",
            "required": [
                "password",
                "passwordAnswer",
                "userId"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "passwordAnswer": {
                    "type": "string",
                    "example": "NTU"
                },
                "userId": {
                    "type": "string",
                    "example": "christine891225"
                },
                "userName": {
                    "type": "string",
                    "example": "Christine Wang"
                }
            }
        },
        "Timeblock": {
            "type": "object",
            "required": [
                "eventId"
            ],
            "properties": {
                "eventId": {
                    "description": "required",
                    "type": "integer",
                    "example": 1
                },
                "normal": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2021-01-01T11:00:00+08:00"
                    ]
                },
                "priority": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2021-01-02T12:00:00+08:00"
                    ]
                }
            }
        },
        "Update": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "passwordAnswer": {
                    "type": "string",
                    "example": "NTU"
                },
                "userName": {
                    "type": "string",
                    "example": "Christine Wang"
                }
            }
        },
        "UpdateEventFormat": {
            "type": "object",
            "properties": {
                "confirmed_timeblocks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2021-01-01T11:00:00+08:00"
                    ]
                },
                "event_id": {
                    "type": "string",
                    "example": "26"
                },
                "event_name": {
                    "type": "string",
                    "example": "Sad 2nd meeting"
                }
            }
        },
        "UpdateTimeblockExportFormat": {
            "type": "object",
            "required": [
                "confirmed_time_blocks",
                "dest_event_id",
                "source_event_id"
            ],
            "properties": {
                "confirmed_time_blocks": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2021-01-01T11:00:00+08:00"
                    ]
                },
                "dest_event_id": {
                    "description": "required",
                    "type": "integer",
                    "example": 26
                },
                "source_event_id": {
                    "description": "required",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "UpdateTimeblockImportFormat": {
            "type": "object",
            "required": [
                "dest_event_id",
                "source_event_id"
            ],
            "properties": {
                "dest_event_id": {
                    "description": "required",
                    "type": "integer",
                    "example": 26
                },
                "source_event_id": {
                    "description": "required",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controller.ForgotInfo": {
            "type": "object",
            "required": [
                "password",
                "passwordAnswer",
                "userId"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "passwordAnswer": {
                    "type": "string",
                    "example": "NTU"
                },
                "userId": {
                    "type": "string",
                    "example": "christine891225"
                }
            }
        },
        "createGroupFormat": {
            "type": "object",
            "required": [
                "group_name"
            ],
            "properties": {
                "event_ids": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "group_name": {
                    "description": "required",
                    "type": "string",
                    "example": "OR-related"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080/",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ThunderMeet APIs",
	Description:      "This is the backend server for the Thundermeet App.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
