definitions:
  EventFormat:
    properties:
      dateOrDays:
        description: required
        example: true
        type: boolean
      endDate:
        description: optional
        example: "2021-01-02T12:00:00.000Z"
        type: string
      endDay:
        description: optional
        example: "7"
        type: string
      endTime:
        description: required
        example: "2100"
        type: string
      eventDescription:
        description: optional
        example: description of event
        type: string
      eventName:
        description: required
        example: OR first meet
        type: string
      isPriorityEnabled:
        description: required
        example: true
        type: boolean
      startDate:
        description: optional
        example: "2021-01-01T12:00:00.000Z"
        type: string
      startDay:
        description: optional
        example: "1"
        type: string
      startTime:
        description: required
        example: "0900"
        type: string
    required:
    - dateOrDays
    - endTime
    - eventName
    - isPriorityEnabled
    - startTime
    type: object
  GetUserResponse:
    properties:
      password_answer:
        example: NTU
        type: string
      status:
        example: 0
        type: integer
      user_id:
        example: christine891225
        type: string
      username:
        example: Christine Wang
        type: string
    required:
    - password_answer
    - status
    - user_id
    - username
    type: object
  Login:
    properties:
      password:
        example: password
        type: string
      userId:
        example: christine891225
        type: string
    required:
    - password
    - userId
    type: object
  Register:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userId:
        example: christine891225
        type: string
      userName:
        example: Christine Wang
        type: string
    required:
    - password
    - passwordAnswer
    - userId
    type: object
  Timeblock:
    properties:
      eventId:
        description: required
        example: 1
        type: integer
      normal:
        description: optional
        example:
        - "2021-01-01T11:00:00.000Z"
        items:
          type: string
        type: array
      priority:
        description: optional
        example:
        - "2021-01-02T12:00:00.000Z"
        items:
          type: string
        type: array
    required:
    - eventId
    type: object
  Update:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userName:
        example: Christine Wang
        type: string
    type: object
  UpdateEventFormat:
    properties:
      confirmed_timeblocks:
        example:
        - "2021-01-01T11:00:00.000Z"
        items:
          type: string
        type: array
      event_id:
        example: "26"
        type: string
      event_name:
        example: Sad 2nd meeting
        type: string
    type: object
  UpdateTimeblockExportFormat:
    properties:
      confirmed_time_blocks:
        description: required
        example:
        - "2021-01-01T11:00:00.000Z"
        items:
          type: string
        type: array
      dest_event_id:
        description: required
        example: 26
        type: integer
      source_event_id:
        description: required
        example: 1
        type: integer
    required:
    - confirmed_time_blocks
    - dest_event_id
    - source_event_id
    type: object
  UpdateTimeblockImportFormat:
    properties:
      dest_event_id:
        description: required
        example: 26
        type: integer
      source_event_id:
        description: required
        example: 1
        type: integer
    required:
    - dest_event_id
    - source_event_id
    type: object
  addGroupEventFormat:
    properties:
      event_ids:
        description: required
        items:
          type: integer
        type: array
    type: object
  controller.ForgotInfo:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userId:
        example: christine891225
        type: string
    required:
    - password
    - passwordAnswer
    - userId
    type: object
  createGroupFormat:
    properties:
      event_ids:
        description: required
        items:
          type: integer
        type: array
      group_name:
        description: required
        example: OR-related
        type: string
    required:
    - group_name
    type: object
  patchGroupFormat:
    properties:
      group_name:
        description: required
        example: SAD-related
        type: string
    required:
    - group_name
    type: object
host: thundermeet-backend.herokuapp.com/
info:
  contact:
    name: Wu, Chien Yin and Yeh, Hsiao Li
  description: This is the backend server for the Thundermeet App.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ThunderMeet APIs
  version: "1.0"
paths:
  /v1/events:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - event
    patch:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to update a event
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/UpdateEventFormat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - event
  /v1/events/:
    post:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to create an event
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/EventFormat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - event
  /v1/events/{event_id}:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: event id
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - event
  /v1/groups/:
    get:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
    post:
      parameters:
      - description: Bearer eyJNoCkSqDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to create an group
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/createGroupFormat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
  /v1/groups/{group_id}:
    delete:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: "7"
        in: path
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
    get:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: "7"
        in: path
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
    patch:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to change the group's name
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/patchGroupFormat'
      - description: "5"
        in: path
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
    post:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to change the group's name
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/addGroupEventFormat'
      - description: "5"
        in: path
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
  /v1/groups/{group_id}/{event_id}:
    delete:
      parameters:
      - description: Bearer eyJhbGcikDCEVLw0xRO8CzTg
        in: header
        name: Authorization
        required: true
        type: string
      - description: "5"
        in: path
        name: group_id
        required: true
        type: integer
      - description: "20"
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - group
  /v1/timeblocks/:
    post:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to create an event
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Timeblock'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
    put:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to update an event
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Timeblock'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
  /v1/timeblocks/{event_id}:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: event id
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
  /v1/timeblocks/{event_id}/preview:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: event id
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
  /v1/timeblocks/export:
    patch:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to import timeblocks
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/UpdateTimeblockExportFormat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
  /v1/timeblocks/import:
    patch:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to import timeblocks
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/UpdateTimeblockImportFormat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - timeblock
  /v1/users:
    patch:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Update'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetUserResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
    post:
      parameters:
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Register'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/login/:
    post:
      parameters:
      - description: The body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/resetPassword:
    patch:
      parameters:
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.ForgotInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
swagger: "2.0"
