definitions:
  Login:
    properties:
      password:
        example: password
        type: string
      userId:
        example: christine891225
        type: string
    required:
    - password
    - userId
    type: object
  Register:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userId:
        example: christine891225
        type: string
      userName:
        example: Christine Wang
        type: string
    required:
    - password
    - passwordAnswer
    - userId
    type: object
  Update:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userName:
        example: Christine Wang
        type: string
    type: object
  controller.ForgotInfo:
    properties:
      password:
        example: password
        type: string
      passwordAnswer:
        example: NTU
        type: string
      userId:
        example: christine891225
        type: string
    required:
    - password
    - passwordAnswer
    - userId
    type: object
host: thundermeet-backend.herokuapp.com/
info:
  contact:
    name: Wu, Chien Yin and Yeh, Hsiao Li
  description: This is the backend server for the Thundermeet App.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ThunderMeet APIs
  version: "1.0"
paths:
  /v1/users:
    patch:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Update'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/:
    get:
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
    post:
      parameters:
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/login/:
    post:
      parameters:
      - description: The body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
  /v1/users/resetPassword:
    patch:
      parameters:
      - description: The body to create a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.ForgotInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - user
swagger: "2.0"
